# https://github.com/softprops/action-gh-release
name: Do Release
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # [!] we need to checkout with tags and commit history
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      - name: Setup dependencies using pip
        run: pip install -r requirements.txt
      - name: 📋 Get Commits since last Release
        id: changes
        uses: simbo/changes-since-last-release-action@v1
          with:
            line-prefix: "* "
            include-hashes: false
      - name: Setup config (using SAMPLE-config.py as config.py)
        id: newversion
        run: |
          NEW_VERSION=$(python release.py -l "${{ steps.changes.outputs.last-tag }}")
          echo "NEW_VERSION=${NEW_VERSION}" >> $GITHUB_OUTPUT
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "${{ steps.newversion.outputs.YOUR_VARIABLE }}"
          make_latest: "true"
          generate_release_notes: true
